export const ERROR_MAP: Record<string, string> = {
  InsufficientBalance: "Insufficient balance",
  AllowanceTooLow: "USDT allowance insufficient",
  MiningEnded: "Mining has ended",
  ExceedCap: "Purchase exceeds remaining supply",
  Paused: "服务维护中，请稍后再试",
  EmptyTokenIds: "请至少选择一张服务卡",
  InvalidPageLimit: "请求的权益记录数量过多",
  InvalidPlan: "权益周期无效",
  NotPositionOwner: "该权益记录不属于当前钱包",
  NotUntrackedFnft: "该服务卡暂不可取回",
  NothingToClaim: "当前没有可确认的权益记录",
  OwnableUnauthorizedAccount: "Wallet is not authorized",
  PositionAlreadyUnstaked: "该服务卡记录已取回",
  PositionLocked: "权益周期尚未结束",
  RewardPoolInsufficient: "权益记录暂不可用，请稍后再试",
  TokenAlreadyStaked: "已选择的服务卡中包含正在权益周期内的卡",
  TooManyNftTransfers: "单次服务卡处理数量过多",
  TooManyPositions: "单次权益记录处理数量过多",
  TooManyTokens: "单条权益记录包含的服务卡过多",
  UnexpectedFnftTransfer: "请通过服务卡权益页面提交，不要直接转入合约",
  ZeroAddress: "Address cannot be zero",
  ZeroAmount: "Amount cannot be zero",
};
