export const ERROR_MAP: Record<string, string> = {
  InsufficientBalance: "Insufficient balance",
  AllowanceTooLow: "USDT allowance insufficient",
  MiningEnded: "Mining has ended",
  ExceedCap: "Purchase exceeds remaining supply",
  Paused: "Contract is paused",
  EmptyTokenIds: "Select at least one F-NFT",
  InvalidPageLimit: "Requested too many positions",
  InvalidPlan: "Invalid staking plan",
  NotPositionOwner: "Position does not belong to this wallet",
  NotUntrackedFnft: "F-NFT is not recoverable",
  NothingToClaim: "No rewards are currently claimable",
  OwnableUnauthorizedAccount: "Wallet is not authorized",
  PositionAlreadyUnstaked: "Position has already been unstaked",
  PositionLocked: "Position is still locked",
  RewardPoolInsufficient: "Reward pool is underfunded",
  TokenAlreadyStaked: "One selected F-NFT is already staked",
  TooManyNftTransfers: "Too many F-NFT transfers in one transaction",
  TooManyPositions: "Too many positions in one transaction",
  TooManyTokens: "Too many F-NFTs in one position",
  UnexpectedFnftTransfer: "Use the staking flow instead of direct transfer",
  ZeroAddress: "Address cannot be zero",
  ZeroAmount: "Amount cannot be zero",
};
