import { type RouteConfig, index, prefix, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("assets", "./routes/assets.tsx"),
  route("rda", "./routes/rda.tsx"),
  route("rda/metadata", "./routes/rda-metadata.tsx"),
  route("nft", "./routes/legacy/nft.tsx"),
  route("nft/metadata", "./routes/legacy/nft-metadata.tsx"),
  route("asset", "./routes/asset/list.tsx"),
  route("asset/metadata", "./routes/asset/metadata.tsx"),
  route("asset/:assetId", "./routes/asset/show.tsx"),
  route("rwa", "./routes/legacy/rwa-list.tsx"),
  route("rwa/metadata", "./routes/legacy/rwa-metadata.tsx"),
  route("rwa/:assetId", "./routes/legacy/rwa-show.tsx"),
  route("admin/asset/storage", "./routes/admin/asset-storage.tsx"),
  route("admin/asset", "./routes/admin/asset.tsx"),
  route("admin/rwa/storage", "./routes/legacy/admin-rwa-storage.tsx"),
  route("admin/rwa", "./routes/legacy/admin-rwa.tsx"),
  route("membership", "./routes/membership.tsx"),
  route("faq", "./routes/faq.tsx"),
  route("points-mall", "./routes/points-mall.tsx"),
  route("staking/storage", "./routes/staking-storage.tsx"),
  route("staking", "./routes/staking.tsx"),
  route("custody", "./routes/custody.tsx"),
  route("liquidity", "./routes/liquidity.tsx"),
  route("meme", "./routes/meme.tsx"),
  ...prefix("support", [
    route("bridge", "routes/support/bridge.tsx"),
  ]),
] satisfies RouteConfig;
